version: '3'
services:
  db:
    image: postgres:12
    ports:
      - 5432:5432
    env_file:
      - ./.env.local
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    command:
      - postgres